spring:
  application:
    name: nacha-ach-processor
  data:
    mongodb:
      database: nachadb
        
application:
  fileWatcher:
    daemon: true
    pollInterval: 5
    quietPeriod: 2
    directory: c:\\workspace\\ach
    